version: '3'
services:

  mule-base:
    image: mule4-docker
    container_name: mule-base
    build:
      context: docker
    command: ["echo", "Base image doesn't need to run"]

  # Elastic stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch-apm-mule
    environment:
      - node.name=elastic-node-1
      - cluster.initial_master_nodes=elastic-node-1
    networks:
      mule:
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana-apm-mule
    networks:
      mule:
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm-server-apm-mule
    networks:
      mule:
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
      - kibana

  component2:
    image: mule4-docker:latest
    container_name: mule-component2
    depends_on:
      - mule-base
      # - apm-server
    networks:
      mule:
    ports:
      - "8081:8081"
    volumes:
      - ./mule/component2/apps:/opt/mule/apps:rw
    environment:
      - ELASTIC_APM_SERVER_URLS=http://apm-server:8200
      - ELASTIC_APM_SERVICE_NAME=component2
      - ELASTIC_APM_SERVICE_VERSION=v1
      - ELASTIC_APM_ENVIRONMENT=dev
      # - ELASTIC_APM_LOG_LEVEL=DEBUG


  component1:
    image: mule4-docker:latest
    container_name: mule-component1
    depends_on:
      - mule-base
      # - apm-server
    networks:
      mule:
    ports:
      - "8082:8082"
    volumes:
      - ./mule/component1/apps:/opt/mule/apps:rw
    environment:
      - ELASTIC_APM_SERVER_URLS=http://apm-server:8200
      - ELASTIC_APM_SERVICE_NAME=component1
      - ELASTIC_APM_SERVICE_VERSION=v1
      - ELASTIC_APM_ENVIRONMENT=dev
      # - ELASTIC_APM_LOG_LEVEL=DEBUG

  loadgen:
    image: appropriate/curl
    depends_on:
      - component1
    networks:
      mule:
    command: ["sh", "-c", "while true; do curl -s http://component1:8082 > /dev/null; sleep 0.1; done"]

networks:
  mule:
